### ISSUE TITLE
- Component error: resources - Integration resources not found.

### ISSUE THREAD

**Issue by aro28** [pkozul/lovelace-floorplan#10]
Hi,
First of all, thank you for doing this great job and helping us to make life easier. 
I copied everything into my /config folder as instructed and changed SVG floorplan file with mine which has all my entities. After that i've tried to check configuration file for errors and i'm getting below error messages..
![Screenshot from 2019-09-28 12-55-18](https://user-images.githubusercontent.com/25077676/65813082-fd9fff80-e1f1-11e9-8f34-1bb2eddcb061.png)

**Comment by exetico** [comment]
Hi

Many things has changed down the line. If you still need help, please resubmit your issue with "up to date" information. And oh, I'm sorry for the (very) late reply!
