### ISSUE TITLE
Does lovelace-floorplan allow to navigate through the Home Assistant tabs?

### ISSUE THREAD

**Issue by arnaupv** [pkozul/lovelace-floorplan#13]
I would like to know if lovelace-floorplan can be used for navigating through the Home Assistant tabs, like picture-elements does. If this is the case, could you provide some yaml example for configuring this feature?

As far as I know, inkscape can be used for adding links into a SVG file. Even though it achieves my goal, the problem is that not only the tab, but the entire home assistant is reloaded (waste of time and resources).

**Comment by exetico** [comment]
Hi @arnaupv 

Did you find the time to make the move to lovelace-floorplan? 

Lovelace-floorplan are added as cards, and you'll be able to add multiple cards, in multiple tabs/pages. I hope that's all you need to here.

All the best :-) 
_Tobias_

**Comment by arnaupv** [comment]
Hi @exetico , thanks for your answer! Yeah, I decided using the card and paginating inside the same card, without changing the card, which is great! Thanks :)

**Comment by exetico** [comment]
Great 🎉

That sounds like a good solution. Could you consider to share the config?

And oh; _Check the new/first-ever release. There's a few new features, too._
