### ISSUE TITLE
HACS compatible

### ISSUE THREAD

**Issue by dolenec** [pkozul/lovelace-floorplan#14]
Please make HACS compatible - so that is easy to install in Home Assistant via Community add-on or HACS.

**Comment by exetico** [comment]
See https://github.com/pkozul/lovelace-floorplan/pull/43 :-)

**Comment by exetico** [comment]
Hi @dolenec 

The first release is now finally here, and ready for HACS, too:
https://github.com/pkozul/lovelace-floorplan/releases/tag/1.0.0

We'll secure to be part of the HACS-official list in a few days, but fell free to add this as a custom repo in HACS.
