### ISSUE TITLE
yaml.min.js - SyntaxError: invalid escape sequence

### ISSUE THREAD

**Issue by SaturnusDJ** [pkozul/lovelace-floorplan#17]
Error in HA:
ERROR (MainThread) [frontend.js.latest.202001082] http://x/local/floorplan/lib/yaml.min.js:1:1478 SyntaxError: invalid escape sequence

**Comment by cjd** [comment]
https://github.com/Domy5/lovelace-floorplan/blob/patch-1/www/floorplan/lib/yaml.min.js has a fix for this
