### ISSUE TITLE
which version to use with HASSIO 0.106 and later

### ISSUE THREAD

**Issue by pilot1981** [pkozul/lovelace-floorplan#24]
Hi,
I have vastest version of HASSIO 0.106, to implement floorplan I have to install:
- lovelace-floorplan
https://github.com/pkozul/lovelace-floorplan

or
-ha-floorplan
https://github.com/pkozul/ha-floorplan

???

regards

**Comment by exetico** [comment]
It depends on your needs. This repo can be used as a lovelace-card. I would use this version. Check our latest release - you can use it with HACS :-)
