### ISSUE TITLE
Animation wrong place

### ISSUE THREAD

**Issue by SBerg1980** [pkozul/lovelace-floorplan#28]
When i use the animation, when the fan is off is on the place i placed it (svg) when i turn on the fan the fan resizes and crops and it not on the same place as when i turn off the fan. Please help.

**Comment by exetico** [comment]
Hi.

Please provide a screenshot with your configuration, including styling and so. Many things can impact animations and positiion(s).

If you still need help with this, kindly let us know - and I'll reopen the issue.
