### ISSUE TITLE
Custom element doesn't exist: floorplan-card  105 works good  109 cannot work 

### ISSUE THREAD

**Issue by lujiashun1** [pkozul/lovelace-floorplan#32]
Custom element doesn't exist: floorplan-card   how to fix it

**Comment by TopoDiFogna** [comment]
see #20 pls

**Comment by exetico** [comment]
Hi all,

We've just pushed the first official version - check the [release overview](https://github.com/pkozul/lovelace-floorplan/releases). I think this is fixed, too :-)
