### ISSUE TITLE
Floorplan not loading

### ISSUE THREAD

**Issue by lklinggaard** [pkozul/lovelace-floorplan#40]
After updating Home Assistant i'm getting this error in the consol log

`ERROR TypeError: Class constructor $ cannot be invoked without 'new'
    at http://192.168.1.36:8123/local/floorplan/lib/floorplan.js?v=1.1.8:276:21`

`Uncaught (in promise) TypeError: Class constructor $ cannot be invoked without 'new'
    at Floorplan.log (VM2910 floorplan.js:1702)
    at Floorplan.handleError (VM2910 floorplan.js:1656)
    at VM2910 floorplan.js:71`

I have replaced all my config files with the newest from the repo. 
Any idea how to fix?

**Comment by truglodite** [comment]
I am having the same issue. I'm not sure exactly which HA update I did before it stopped working. I don't have logs to show either. 

I can add that the floorplan does work more consistently on my PC, and the problem appears to mostly affect my android phone (w/ chrome mobile). On my phone, the floorplan will only show up once, the first time I access it after editing the custom card yaml in lovelace. As soon as I hit refresh (on the android), the floorplan disappears and will not show up again until I 'touch' the lovelace card yaml. This behavior is very repeatable. Everything else with my HA instance is working as it should.

Any further work/info I can provide I will be happy to do. FWIW, I'm using the latest HAOS (pi3b+ w/ usb ssd), the latest HA, and the current version of lovelace floorplan from here (apparently last merged 8months ago for fixes related to HA 0.106). If there are any logs I can turn on/submit here, please let me know how to do that.

**Comment by exetico** [comment]
Hi 

Could you please give it a new change, in the latest release? I've not seen anything like that, and not floorplan.js are integrated in the dist-file. 

Please reopen the issues, if you're still facing issues. That's includes you too, @truglodite  :-)
