### ISSUE TITLE
Using JavaScript template literals

### ISSUE THREAD

**Issue by markgolding** [pkozul/lovelace-floorplan#41]
code = " $(element).find(\`[id="${name}"]\`)[0]"

when /www/floorplan/lib/floorplan.js evaluate(code, entityId, svgElement) is called

let functionBody = (**code.indexOf('${') >= 0)** ? `\`${code}\`;` : code;

then the whole JavaScript code gets wrapped with ``

**Comment by exetico** [comment]
Hi,

We've just pushed the first official version of the solution - check the [release overview](https://github.com/pkozul/lovelace-floorplan/releases). I think this is fixed, too.
