### ISSUE TITLE
card very small

### ISSUE THREAD

**Issue by guyyar89** [pkozul/lovelace-floorplan#42]
hey,

thanks for your lovelace card but wht its only small card show me?
how to bigger?

**Comment by Harwesta** [comment]
You need to add parameter 
 `panel: true`

to bottom your's lovelace floorplan config (use a raw editor). As examle: 
```
    icon: 'mdi:floor-plan'
    id: system
    title: Floorplan
    panel: true
```

**Comment by guyyar89** [comment]
thanks
