### ISSUE TITLE
Feature Request: Long Click/Press

### ISSUE THREAD

**Issue by noxhirsch** [pkozul/lovelace-floorplan#9]
Hi,
at first thank you for this amazing lovelace card!
It would be amazing to have an additional long click/press function. So you could e.g. switch a light with short press and open more info (to dim, color, ...) on long press.

Thank you in advance! :)

**Comment by Alfiegerner** [comment]
You can try this:

https://github.com/Alfiegerner/lovelace-floorplan/tree/long_click

add long_click: true to your rule and it should open more-info.

Not ready for a pull request, long press doesn't work perfectly on desktop but good on chrome android mobile which is all I want it for.

Can definitely be improved.  I've added a shortClick and longClick events that we listen for in modified floorplan, but even so slight hax delay of 300 ms needed to to longClick event handler to make it work.

**Comment by exetico** [comment]
Wuhuuuuu. We've a match, for our new release. Check it out:
https://github.com/pkozul/lovelace-floorplan/releases

Notes about `long_click` are added in the README.md, too :-)
